### ISSUE TITLE
posix-uefi library

### ISSUE THREAD

**Issue by staalmannen** [yoppeh/efi-clang#4]
Hi

I thought you might be interested in this:
https://gitlab.com/bztsrc/posix-uefi/

It can also generate native EFI format when clang/lld is used.

**Comment by staalmannen** [comment]
It does not provide UEFI headers itself so it might be a really good complement to efi-clang that does provide the headers,

**Comment by yoppeh** [comment]
That’s pretty cool. Thanks for letting me know about it. My thing is really just simply an example of how to build UEFI apps with clang/llld and doesn’t have the startup and library… which is what I intended.

Seems like they’re going for a different approach where things are implemented as POSIX functions and you wouldn’t necessarily need to mess with the headers and raw UEFI calls. Though, you’d probably end up having to anyway, since I doubt the entire UEFI spec would be covered by this sort of implementation. Maybe further down the road.

Have a good one!
Warren
